<?php declare(strict_types=1);

/*
 * This file is part of ptomulik/icon_field.
 *
 * Copyright (c) Paweł Tomulik <ptomulik@meil.pw.edu.pl>
 *
 * View the LICENSE file for full copyright and license information.
 */

/**
 * Implements hook_theme().
 *
 * @param mixed $existing
 * @param mixed $type
 * @param mixed $theme
 * @param mixed $path
 */
function icon_field_theme($existing, $type, $theme, $path)
{
    return [
        'icon_field' => [
            'render element' => 'element',
        ],
    ];
}

function icon_field_preprocess_icon_field(&$variables)
{
    $variables['link'] = $variables['element']['#link'] ?? '';
    $variables['content'] = $variables['element']['#content'] ?? [];
}
