<?php

/**
 * @file
 */

declare(strict_types=1);

/**
 * Implements hook_theme().
 *
 * @param mixed $existing
 * @param mixed $type
 * @param mixed $theme
 * @param mixed $path
 */
function icon_field_theme($existing, $type, $theme, $path) {
  return [
    'icon_field' => [
      'render element' => 'element',
    ],
  ];
}

/**
 *
 */
function icon_field_preprocess_icon_field(&$variables) {
  $variables['link'] = $variables['element']['#link'] ?? '';
  $variables['content'] = $variables['element']['#content'] ?? [];
}
